//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleCallingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAge { get; set; }
        public string Salary { get; set; }
        public string City { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    }
}
